#!/bin/sh
set -e
export LC_ALL=C

#scripts/fribidi-config
#scripts/fribidi-build "$@"
scripts/vvdec-config
scripts/vvdec-build "$@"
scripts/libplacebo-config
scripts/libplacebo-build "$@"
scripts/libass-config
scripts/libass-build "$@"
scripts/fdk-aac-config
scripts/fdk-aac-build "$@"
scripts/libjxl-config
scripts/libjxl-build "$@"
scripts/dav1d-config
scripts/dav1d-build "$@"
scripts/ffmpeg-config
scripts/ffmpeg-build "$@"
scripts/mpv-config
scripts/mpv-build "$@"
