#!/bin/sh
set -e

BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/dav1d_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/dav1d_options) "$@"
    unset -v IFS
fi

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/dav1d

meson setup build --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" "$@"
