#!/bin/sh
set -e
BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/fdk-aac_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/fdk-aac_options) "$@"
    unset -v IFS
fi

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/fdk-aac

./autogen.sh --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" "$@"
./configure  --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" "$@"

