#!/bin/sh
set -e
BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/vvdec_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/vvdec_options) "$@"
    unset -v IFS
fi

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/vvdec
mkdir build && cd build
# Later libass doesn't automatically run configure with autogen.sh anymore

cmake .. -DCMAKE_INSTALL_PREFIX="$BUILD/build_libs/" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DBUILD_SHARED_LIBS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-flto -O3 -march=x86-64-v3" -DCMAKE_C_FLAGS="-flto -O3 -march=x86-64-v3 -pipe -fno-plt" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld"
